### PR TITLE
Copy to clipboard functionality

### PR DESCRIPTION
**Pull request by yangshun**
Added copy to clipboard functionality using ZeroClipboard. I tried to style the button to emulate the style of the page, but feel free to further modify the styles to suit your preference.

### CODE REVIEW

**Comment by yangshun** [comment]
Finally fixed the bug. Tested in Chrome 41, Firefox 36 and Safari 8. Demo can be viewed here: http://yangshun.im/csshexagon/

screen shot 2015-03-28 at 8 35 20 pm

**Comment by brenna** [comment]
Thanks for the update. Your live example does indeed work in Firefox, but if I check out your PR branch and upload to a [test url](http://www.brennaobrien.com/csshextest/), I'm still not getting any copy in FF. Is anything missing from the PR compared to what's on your live test?

**Comment by yangshun** [comment]
Hey @brenna , that's not the latest state of PR branch. If you look at the `controller.js` line 204, it should contain `buttonEl.textContent`. In the test url you have, it contains `buttonEl.innerText`, which is the previous version that doensn't work on FF.

**Comment by brenna** [comment]
@yangshun whoops, my bad. merged and deployed. thanks again!

**Comment by yangshun** [comment]
You're welcome! Thanks for this hexagon generator! :smile:

**Pull request merged**
